# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

user = User.create! email: 'thomas.taege@eneraque.com', password: 'M3ad0wmuff!n', password_confirmation: 'M3ad0wmuff!n'
user = User.create! email: 'laura.pringle@eneraque.com', password: 'largespeechseendoes', password_confirmation: 'largespeechseendoes'
user = User.create! email: 'jeremy.pringle@eneraque.com', password: 'shootlovelycouplerefer', password_confirmation: 'shootlovelycouplerefer'
user = User.create! email: 'aed.mac.phaidin@eneraque.com', password: 'warmsuggestcoalhurried', password_confirmation: 'warmsuggestcoalhurried'
user = User.create! email: 'andrew.standley@eneraque.com', password: 'writebarefurtherbread', password_confirmation: 'writebarefurtherbread'
user = User.create! email: 'andy.gardner@eneraque.com', password: 'fullyofconnectednoon', password_confirmation: 'fullyofconnectednoon'
user = User.create! email: 'antoinette.iles@eneraque.com', password: 'settlersdepthsnaketell', password_confirmation: 'settlersdepthsnaketell'
user = User.create! email: 'bronte.pringle@eneraque.com', password: 'noddedyoungchartusually', password_confirmation: 'noddedyoungchartusually'
user = User.create! email: 'craig.mclauchlan@eneraque.com', password: 'boatwakefunweekend', password_confirmation: 'boatwakefunweekend'
user = User.create! email: 'daniel.parker@eneraque.com', password: 'dustgasstarminute', password_confirmation: 'dustgasstarminute'
user = User.create! email: 'daniel.woodford@eneraque.com', password: 'fifteenbetweentenfix', password_confirmation: 'fifteenbetweentenfix'
user = User.create! email: 'david.cooper@eneraque.com', password: 'severalexclaimedcakenice', password_confirmation: 'severalexclaimedcakenice'
user = User.create! email: 'david.leal@eneraque.com', password: 'bigfishjighard', password_confirmation: 'bigfishjighard'
user = User.create! email: 'dev.pilcharambath@eneraque.com', password: 'coursenearlyfairterm', password_confirmation: 'coursenearlyfairterm'
user = User.create! email: 'euan.mcgregor@eneraque.com', password: 'alphabetstopblanksudden', password_confirmation: 'alphabetstopblanksudden'
user = User.create! email: 'grant.lihou@eneraque.com', password: 'largereasiertoptie', password_confirmation: 'largereasiertoptie'
user = User.create! email: 'guy.pringle@eneraque.com', password: 'floorswungparticularpattern', password_confirmation: 'floorswungparticularpattern'
user = User.create! email: 'hilton.cooper@eneraque.com', password: 'beerathertwelveadventure', password_confirmation: 'beerathertwelveadventure'
user = User.create! email: 'jim.pringle@eneraque.com', password: 'theyabilitycompletelyhistory', password_confirmation: 'theyabilitycompletelyhistory'
user = User.create! email: 'jonathan.pringle@eneraque.com', password: 'helpfulouteramhot', password_confirmation: 'helpfulouteramhot'
user = User.create! email: 'manfred.beyrer@eneraque.com', password: 'tapebeanfoxfeature', password_confirmation: 'tapebeanfoxfeature'
user = User.create! email: 'noel.rosario@eneraque.com', password: 'writinglotworeherself', password_confirmation: 'writinglotworeherself'
user = User.create! email: 'ray.verburgt@eneraque.com', password: 'aidlovebroadbuilding', password_confirmation: 'aidlovebroadbuilding'
user = User.create! email: 'richard.cranswick@eneraque.com', password: 'believedfunnyoccurcentral', password_confirmation: 'believedfunnyoccurcentral'
user = User.create! email: 'steve.froome@eneraque.com', password: 'capturedgrasstideprinciple', password_confirmation: 'capturedgrasstideprinciple'
user = User.create! email: 'stuart.pringle@eneraque.com', password: 'visitfullygivehope', password_confirmation: 'visitfullygivehope'
user = User.create! email: 'tony.millar@eneraque.com', password: 'camptonightpagedone', password_confirmation: 'camptonightpagedone'
user = User.create! email: 'trixie.pringle@eneraque.com', password: 'drinktunepastcertain', password_confirmation: 'drinktunepastcertain'
user = User.create! email: 'wesley.mcnaughton@eneraque.com', password: 'amongranchfairlybear', password_confirmation: 'amongranchfairlybear'
user = User.create! email: 'william.lister@eneraque.com', password: 'structurenationscorefact', password_confirmation: 'structurenationscorefact'
user = User.create! email: 'luminita.kopf@eneraque.com', password: 'powerbellracebelow', password_confirmation: 'powerbellracebelow'
user = User.create! email: 'mohamed.manzoor@eneraque.com', password: 'lookoccurpinktrip', password_confirmation: 'lookoccurpinktrip'
user = User.create! email: 'brad.bailey@eneraque.com', password: 'spacelistbellcave', password_confirmation: 'spacelistbellcave'
user = User.create! email: 'darren.nankivell@eneraque.com', password: 'amlackwonderverb', password_confirmation: 'amlackwonderverb'
user = User.create! email: 'nick.fletcher@eneraque.com', password: 'listbreathpainwrote', password_confirmation: 'listbreathpainwrote'
user = User.create! email: 'john.mccarthy@eneraque.com', password: 'suppermasslunchrun', password_confirmation: 'suppermasslunchrun'
user = User.create! email: 'rebecca.frost@eneraque.com', password: 'storepocketbirdhouse', password_confirmation: 'storepocketbirdhouse'
